// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuONgWFNa2C0fvk1JrkfJo3kue4wbtnhc',
    appId: '1:14849869102:web:ca2c996664132884d1e6bf',
    messagingSenderId: '1009982600478',
    projectId: 'product-db-357d9',
    authDomain: 'product-db-357d9.firebaseapp.com',
    databaseURL: 'https://product-db-357d9-default-rtdb.firebaseio.com/',
    storageBucket: 'product-db-357d9.appspot.com',
    measurementId: 'G-HYV87SHREB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tBX2wI43DugTM7t5YXNtzAXAf5BF9og',
    appId: '1:14849869102:android:3de9ced51fd7114fd1e6bf',
    messagingSenderId: '1009982600478',
    projectId: 'product-db-357d9',
    databaseURL: 'https://product-db-357d9-default-rtdb.firebaseio.com/',
    storageBucket: 'product-db-357d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkug8Vye724Piyvmu2qpoR4eOBnyyYJ1A',
    appId: '1:14849869102:ios:310f74c9520217a5d1e6bf',
    messagingSenderId: '1009982600478',
    projectId: 'product-db-357d9',
    databaseURL: 'https://product-db-357d9-default-rtdb.firebaseio.com/',
    storageBucket: 'product-db-357d9.appspot.com',
    iosBundleId: 'com.product.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkug8Vye724Piyvmu2qpoR4eOBnyyYJ1A',
    appId: '1:1009982600478:ios:4b320617e11e1c84fb450f',
    messagingSenderId: '1009982600478',
    projectId: 'product-db-357d9',
    databaseURL: 'https://product-db-357d9-default-rtdb.firebaseio.com/',
    storageBucket: 'product-db-357d9.appspot.com',
    iosBundleId: 'com.product.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuONgWFNa2C0fvk1JrkfJo3kue4wbtnhc',
    appId: '1:14849869102:web:2abe8a6f8c2dc6c1d1e6bf',
    messagingSenderId: '1009982600478',
    projectId: 'product-db-357d9',
    authDomain: 'product-db-357d9.firebaseapp.com',
    databaseURL: 'https://product-db-357d9-default-rtdb.firebaseio.com/',
    storageBucket: 'product-db-357d9.appspot.com',
    measurementId: 'G-EKZ2PPY8Y1',
  );
}
